---
output:
  pdf_document: default
  html_document: default
---


```{r, message = FALSE}

library(tidyverse)
library(reticulate)
library(ggwordcloud)


devtools::load_all()

```


# Setup reticulate


```{r}

# conda_create("mel2word-env", python_version = "3.10")

# conda_install(
#   "mel2word-env",
#   packages = c(
#     "wordcloud",
#     "requests",
#     "urllib3",
#     "charset_normalizer",
#     "scikit-learn",
#.    "gensim",
#      "pretty_midi"
#   ),
#   pip = TRUE
# )

# (restart R after)

# conda_list()

```


```{r}

use_condaenv("mel2word-env", required = TRUE)



```



```{r}


# Tell reticulate where your local Mel2Word code lives:
mel2word_path <- "/Users/sebsilas/Mel2word"

# Add Mel2Word folder to Python PATH
py_run_string(sprintf("import sys; sys.path.insert(0, '%s')", mel2word_path))

# Now import the module
mel2word <- import("mel2word")
pretty_midi <- import("pretty_midi")


# Example: list functions/objects
reticulate::py_list_attributes(mel2word)

```


```{r}

# ------------------------------------------------------------
# Write MIDI using embedded Python
# ------------------------------------------------------------

write_midi_pretty <- function(mel_df,
                              file,
                              tempo_bpm = 120) {

  if (!all(c("pitch", "duration") %in% names(mel_df))) {
    stop("mel_df must contain columns: pitch, duration")
  }

  mel_df$duration <- round(mel_df$duration / 0.25) * 0.25

  # Pass data to Python
  py$mel_pitch <- as.integer(mel_df$pitch)
  py$mel_dur   <- as.numeric(mel_df$duration)
  py$outfile   <- file
  py$tempo     <- as.numeric(tempo_bpm)

  py_run_string("
import pretty_midi

seconds_per_beat = 60.0 / tempo

pm = pretty_midi.PrettyMIDI()
instrument = pretty_midi.Instrument(program=0)

onset = 0.0

for p, d in zip(mel_pitch, mel_dur):
    dur_sec = d * seconds_per_beat
    note = pretty_midi.Note(
        velocity=100,
        pitch=int(p),
        start=onset,
        end=onset + dur_sec
    )
    instrument.notes.append(note)
    onset += dur_sec

pm.instruments.append(instrument)
pm.write(outfile)
")
}

# ------------------------------------------------------------
# Main wrapper
# ------------------------------------------------------------

mel2word_tokenise <- function(mel_df,
                              dictionary_path,
                              feat = 3,
                              dic_size = 100,
                              tempo_bpm = 120) {

  tmp_midi <- tempfile(fileext = ".mid")
  on.exit(unlink(tmp_midi), add = TRUE)

  write_midi_pretty(
    mel_df,
    file = tmp_midi,
    tempo_bpm = tempo_bpm
  )

  M2W <- mel2word$get_M2W_from_midipath(
    tmp_midi,
    feature_option = as.integer(feat)
  )

  dictionary <- mel2word$load_dictionary(dictionary_path)

  tokens <- mel2word$get_M2W_tokens(
    M2W,
    dictionary,
    dic_size = as.integer(dic_size),
    feat = as.integer(feat)
  )

  py_to_r(tokens)
}

# ------------------------------------------------------------
# Example
# ------------------------------------------------------------

mel_df <- data.frame(
  pitch    = c(60, 62, 64, 65, 67),
  duration = c(1, 1, 1, 1, 2)
)

tokens <- mel2word_tokenise(
  mel_df,
  dictionary_path = "/Users/sebsilas/Mel2word/Dictionary/Dictionary_all.pkl",
  feat = 3
)

print(tokens)

```


```{r}

dict_tbl <- read_mel2word_dictionary(
  "/Users/sebsilas/Mel2word/Dictionary/Dictionary_all.pkl",
  tidy = TRUE
)

dplyr::count(dict_tbl, length)

```

```{r}

dict_tbl %>% 
    ggplot(aes(x = length)) +
      geom_histogram(breaks = 1:11)

```

```{r}

# ggplot based word cloud for pdf rendering
dict_tbl %>%
  rename(word = token) %>%
  slice_max(freq, n = 100) %>% 
  ggplot(aes(label = word, size = freq, color = freq)) +
  geom_text_wordcloud(area_corr = TRUE) +
  scale_size_area(max_size = 18) +
  scale_color_viridis_c(option = "C", guide = "none") +
  theme_minimal(base_size = 14) +
  theme(
    plot.background = element_blank(),
    panel.grid = element_blank()
  )

```


```{r}

dictionary_path <- "/Users/sebsilas/Mel2word/Dictionary/Dictionary_all.pkl"

melodies <- list(
  data.frame(pitch = c(60, 62, 64, 65, 67),
             duration = c(1, 1, 1, 1, 2)),
  data.frame(pitch = c(60, 59, 57, 55, 52),
             duration = c(1, 1, 1, 1, 2))
)

# Tokenise corpus
token_corpus <- lapply(
  melodies,
  mel2word_tokenise,
  dictionary_path = dictionary_path,
  feat = 3
)

py_run_string("
import gensim
from gensim.models import Word2Vec
import mel2word
mel2word.Word2Vec = Word2Vec
")

# Train Word2Vec (paper parameters)
w2v_model <- train_m2w_w2v(token_corpus)


```


```{r}

# Get melody embeddings
melody_embeddings <- lapply(
  token_corpus,
  get_melody_embedding,
  model = w2v_model
)

```

```{r}

cosine_sim_exp <- function(x, y, beta = 5) {
  if (length(x) == 0 || length(y) == 0) return(NA_real_)
  if (sum(x^2) == 0 || sum(y^2) == 0) return(NA_real_)
  
  raw <- sum(x * y) / (sqrt(sum(x^2)) * sqrt(sum(y^2)))
  d <- 1 - raw
  exp(-beta * d)
}

# Compute similarity matrix
sim_matrix <- outer(
  seq_along(melody_embeddings),
  seq_along(melody_embeddings),
  Vectorize(function(i, j)
    cosine_sim_exp(melody_embeddings[[i]],
               melody_embeddings[[j]]))
)

sim_matrix


```



# Try with real melsim paper corpus


```{r}

load(file = '~/melsim_paper/data/melsim_paper_data.rda')

mel_sim_metrics <- mel_sim_metrics[, c(1:136, 139:ncol(mel_sim_metrics))] # Handle dup col

rm(exp1_so_users, 
     exp1_demographic_dat, 
     exp1_raw,
     sim_ratings, 
     sim_ratings_midi, 
     sim_ratings_audio,
     saa_dataset, 
     exp1_audio_feats)


```


```{r, eval = FALSE}

target_tokens <- lapply(
  exp1_target_melody_objs,
  function(mel) {
      mel2word_tokenise(mel$data,
                        dictionary_path = dictionary_path,
                        feat = 3)
  }
)



recall_tokens <- lapply(
  exp1_query_melody_objs,
  function(mel) {
    tryCatch({
      mel2word_tokenise(mel$data,
                        dictionary_path = dictionary_path,
                        feat = 3)
    }, error = function(err) {
      logging::logerror("err: %s", err)
      NA
    })
      
  }
)



```


```{r, eval = FALSE}

all_tokens <- c(target_tokens, recall_tokens) %>% 
  unname()

token_lens <- map_int(all_tokens, length)

all_tokens <- all_tokens[-which(token_lens == 0)]

token_bool <- map_lgl(all_tokens, is.logical)

all_tokens <- all_tokens[-which(token_bool)]

# token_corpus

main_w2v_model <- train_m2w_w2v(all_tokens)


save(main_w2v_model, file = "main_w2v_model.rda")

```


```{r, eval = FALSE}

load(file = "main_w2v_model.rda")

```

```{r}

# t <- get_melody_embedding(target_tokens[1], model = main_w2v_model)

# cosine_sim(t[1], t[1])

```

```{r, eval = FALSE}

# Get melody embeddings
target_embeddings <- lapply(
  target_tokens,
  get_melody_embedding,
  model = main_w2v_model
)

recall_embeddings <- lapply(
  recall_tokens,
  get_melody_embedding,
  model = main_w2v_model
)

```



```{r, eval = FALSE}

# Compute similarity matrix
full_sim_matrix <- map_dfr(seq_along(target_embeddings), function(i) {
  
  sim <- cosine_sim_exp(target_embeddings[[i]], recall_embeddings[[i]])
  
  tibble(
    melody1 = names(target_embeddings)[i],
    melody2 = names(recall_embeddings)[i],
    sim_mel2word = sim
  )
}) %>% 
  mutate(sim_mel2word = case_when(is.nan(sim_mel2word) ~ NA, TRUE ~ sim_mel2word))


save(full_sim_matrix, file = "full_sim_matrix.rda")

```


```{r}

load(file = "full_sim_matrix.rda")

full_sim_matrix <- full_sim_matrix %>%
  mutate(
    melody1 = as.integer(melody1),
    melody2 = as.integer(melody2),
    pair_id = pair_index(melody1, melody2)
    ) %>%
  distinct(pair_id, .keep_all = TRUE) %>% 
  dplyr::select(-melody1, -melody2)

```

```{r}


mel_sim_metrics <- mel_sim_metrics %>% 
  mutate(pair_id = pair_index(melody1, melody2)) %>% 
  left_join(full_sim_matrix, by = 'pair_id')

```


```{r}

mel_sim_metrics %>% 
  ggplot(aes(x = sim_mel2word)) +
    geom_histogram()

```


```{r}

cor(mel_sim_metrics$sim_opti3, mel_sim_metrics$sim_mel2word, use = 'pairwise.complete.obs')

```



```{r}

# save(mel_sim_metrics, file = "mel_sim_metrics_temp.rda")

```



