similarity_measures <- list(
  ngrukkon = melsim::sim_measure_factory$new(full_name = "ngram-int-3-ukkon",
                                             name = "ngrukkon",
                                             type = "set_based",
                                             transformation = "ngrams",
                                             parameters = list(transformation = "int", ngram_length = 3),
                                             sim_measure = "ukkon",
                                             transposition_invariant = T,
                                             tempo_invariant = T),
  ngrsumc = melsim::sim_measure_factory$new(full_name = "ngram-int-3-ukkon",
                                             name = "ngrsumc",
                                             type = "set_based",
                                             transformation = "ngrams",
                                             parameters = list(transformation = "int", ngram_length = 3),
                                             sim_measure = "sum_common",
                                             transposition_invariant = T,
                                             tempo_invariant = T),
  ngrcoord = melsim::sim_measure_factory$new(full_name = "ngram-int-3-ukkon",
                                             name = "ngrccord",
                                             type = "set_based",
                                             transformation = "ngrams",
                                             parameters = list(transformation = "int", ngram_length = 3),
                                             sim_measure = "count_distinct",
                                             transposition_invariant = T,
                                             tempo_invariant = T),

  ngrjacc = melsim::sim_measure_factory$new(full_name = "ngram-int-3-jaccard",
                                                  name = "ngrjacc",
                                                  type = "set_based",
                                                  transformation = "ngrams",
                                                  parameters = list(transformation = "int", ngram_length = 3),
                                                  sim_measure = "Jaccard",
                                                  transposition_invariant = T,
                                                  tempo_invariant = T),

  ngrdists = melsim::sim_measure_factory$new(full_name = "ngram-int-3-distribution-similarity",
                                                  name = "ngrdist",
                                                  type = "set_based",
                                                  transformation = "ngrams",
                                                  parameters = list(transformation = "int", ngram_length = 3),
                                                  sim_measure = "dist_sim",
                                                  transposition_invariant = T,
                                                  tempo_invariant = T),

  ngram_int_ioi_dist = melsim::sim_measure_factory$new(full_name = "ngram-int|ioi_cass-3-distribution-similarity",
                                             name = "ngram_int_ioi_dist",
                                             type = "set_based",
                                             transformation = "ngrams",
                                             parameters = list(transformation = "int_X_ioi_class", ngram_length = 3),
                                             sim_measure = "dist_sim",
                                             transposition_invariant = T,
                                             tempo_invariant = T),

  ngram_ioi_class_dist = melsim::sim_measure_factory$new(full_name = "ngram-ioi_cass-3-distribution-similarity",
                                                       name = "ngram_ioi_class_dist",
                                                       type = "set_based",
                                                       transformation = "ngrams",
                                                       parameters = list(transformation = "ioi_class", ngram_length = 3),
                                                       sim_measure = "dist_sim",
                                                       transposition_invariant = T,
                                                       tempo_invariant = T),

  harmcore = melsim::sim_measure_factory$new(full_name = "implicit-harmonies-edit-distance",
                                             name = "harmcore",
                                             type = "sequence_based",
                                             transformation = "implicit_harmonies",
                                             parameters = list(),
                                             sim_measure = "edit_sim_utf8",
                                             transposition_invariant = T,
                                             tempo_invariant = T),

  rhytfuzz = melsim::sim_measure_factory$new(full_name = "ioi-class-edit-distance",
                                             name ="rhytfuzz",
                                             type = "sequence_based",
                                             transformation = "ioi_class",
                                             parameters = list(),
                                             sim_measure = "edit_sim_utf8",
                                             transposition_invariant = T,
                                             tempo_invariant = T),

  diffed = melsim::sim_measure_factory$new(full_name = "int-edit-distance",
                                           name ="diffed",
                                           type = "sequence_based",
                                           transformation = "int",
                                           parameters = list(),
                                           sim_measure = "edit_sim_utf8",
                                           transposition_invariant = T,
                                           tempo_invariant = T),

  ngram_tversky = melsim::sim_measure_factory$new(full_name = "ngram-int-3-tversky",
                                                  name = "ngrtvers",
                                                  type = "set_based",
                                                  transformation = "ngrams",
                                                  parameters = list(transformation = "int",
                                                                    ngram_length = 3,
                                                                    ngram_db = "melsim::int_ngrams_berkowitz",
                                                                    alpha = 1,
                                                                    beta = 1),
                                                  sim_measure = "Tversky",
                                                  transposition_invariant = T,
                                                  tempo_invariant = T),

  ngram_tversky_auto = melsim::sim_measure_factory$new(full_name = "ngram-int-3-tversky",
                                                       name = "ngrtvera",
                                                       type = "set_based",
                                                       transformation = "ngrams",
                                                       parameters = list(transformation = "int",
                                                                         ngram_length = 3,
                                                                         ngram_db = "melsim::int_ngrams_berkowitz",
                                                                         alpha = "auto",
                                                                         beta = "auto"),
                                                       sim_measure = "Tversky",
                                                       transposition_invariant = T,
                                                       tempo_invariant = T),

  pmips = melsim::sim_measure_factory$new(full_name = "pat_savage_pmi",
                                          name = "pmips",
                                          type = "sequence_based",
                                          transformation = "pitch",
                                          parameters = list(optimizer = "transpose"),
                                          sim_measure = "pmi",
                                          transposition_invariant = T,
                                          tempo_invariant = T),

  rawed = melsim::sim_measure_factory$new(full_name = "pitch-edit-distance",
                                          name = "rawed",
                                          type = "sequence_based",
                                          transformation = "pitch",
                                          parameters = list(optimizer = "transpose"),
                                          sim_measure = "edit_sim_utf8",
                                          transposition_invariant = T,
                                          tempo_invariant = T),

  const = melsim::sim_measure_factory$new(full_name = "const",
                                          name = "const",
                                          type = "special",
                                          transformation = "none",
                                          parameters = list(),
                                          sim_measure = "const",
                                          transposition_invariant = T,
                                          tempo_invariant = T),

  opti3 = melsim::sim_measure_factory$new(full_name = "opti3",
                                          name = "opti3",
                                          type = "linear_combination",
                                          transformation = "none",
                                          parameters = list(keep_singles = T),
                                          sim_measure = "0.505 *  ngrukkon + 0.417  * rhytfuzz + 0.24  * harmcore - 0.146 * const",
                                          transposition_invariant = T,
                                          tempo_invariant = T))

usethis::use_data(similarity_measures, overwrite = T)
